1:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
2:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
3:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
4:
  length: 2mm
  weight: Too small to calculate
  size: poppy seed
  image:
  symptoms: Nausea, Bloating, Tender Breasts
  baby_info:
5:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
6:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
7:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
8:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
9:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
10:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
11:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
12:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
13:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
14:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
15:
  length: 16.7cm
  weight: 117 grams
  size: Apple
  image: apple.jpg
  symptoms: Headaches, Tender Breasts, High Sex Drive
  baby_info: Your baby is starting to sense light!
16:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
17:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
18:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
19:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
20:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
21:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
22:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
23:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
24:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
25:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
26:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
27:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
28:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
29:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
30:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
31:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
32:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
33:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
34:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
35:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
36:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
37:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
38:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
39:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
40:
  length:
  weight:
  size:
  image:
  symptoms:
  baby_info:
